// SpecialtyData.js

const SpecialityData = [
    { code: "0", speciality: "M. RADIOLOGY & DIAGNOSIS" },
    { code: "1", speciality: "SPECIALITY NOT KNOWN" },
    { code: "2", speciality: "ANAESTHESIOLOGY" },
    { code: "3", speciality: "ANATOMY" },
    { code: "4", speciality: "BACTERIOLOGY" },
    { code: "5", speciality: "BIO-CHEMISTRY" },
    { code: "6", speciality: "CARDIO THORACIC SURGERY" },
    { code: "7", speciality: "CARDIOLOGY" },
    { code: "8", speciality: "CHEST DISEASES" },
    { code: "9", speciality: "COMMUNITY MEDICINE" },
    { code: "10", speciality: "CRON SURGERY" },
    { code: "11", speciality: "DERMATOLOGY" },
    { code: "12", speciality: "E.N.T." },
    { code: "13", speciality: "ENDOCRINOLOGY" },
    { code: "14", speciality: "EPIDEMIOLOGY" },
    { code: "15", speciality: "FAMILY MEDICINE" },
    { code: "16", speciality: "FORENSIC MEDICINE" },
    { code: "17", speciality: "G. SURGERY" },
    { code: "18", speciality: "GASTRO-ENTEROLOGY" },
    { code: "19", speciality: "GENERAL MEDICINE" },
    { code: "20", speciality: "HAEMATOLOGY" },
    { code: "21", speciality: "HOSPITAL ADMINISTRATION" },
    { code: "22", speciality: "HUMAN NUTRITION" },
    { code: "23", speciality: "IMMUNOLOGY" },
    { code: "24", speciality: "MEDICINE" },
    { code: "25", speciality: "MICROBIOLOGY" },
    { code: "26", speciality: "NEPHROLOGY" },
    { code: "27", speciality: "NEUROLOGY" },
    { code: "28", speciality: "NUCLEAR CARDIOLOGY" },
    { code: "29", speciality: "NUCLEAR MEDICINE" },
    { code: "30", speciality: "OBSTETRICS & GYNAECOLOGY" },
    { code: "31", speciality: "ONCOLOGY" },
    { code: "32", speciality: "OPHTHALMOLOGY" },
    { code: "33", speciality: "ORTHOPAEDICS" },
    { code: "34", speciality: "PAEDIATRICS" },
    { code: "35", speciality: "PATHOLOGY" },
    { code: "36", speciality: "PHARMACOLOGY" },
    { code: "37", speciality: "PHYSIOLOGY" },
    { code: "38", speciality: "PLASTIC SURGERY" },
    { code: "39", speciality: "PROCTOLOGY" },
    { code: "40", speciality: "PSYCHIATRY" },
    { code: "41", speciality: "RADIOLOGY" },
    { code: "42", speciality: "RHEUMATOLOGY" },
    { code: "43", speciality: "SOCIAL & PREV. MEDICINE" },
    { code: "44", speciality: "SPORTS MEDICINE" },
    { code: "45", speciality: "SURGERY" },
    { code: "46", speciality: "TROPICAL MEDICINE" },
    { code: "47", speciality: "UROLOGY" },
    { code: "48", speciality: "VIROLOGY" },
    { code: "49", speciality: "NOT APPLICABLE" },
    { code: "50", speciality: "MEDICINE" },
    { code: "51", speciality: "DIABETOLOGY" },
    { code: "52", speciality: "LARYNGOLOGY & OTOLOGY" },
    { code: "53", speciality: "INDUSTRIAL HEALTH" },
    { code: "54", speciality: "LEPROSY" },
    { code: "55", speciality: "TUBERULOSIS&RESPIRATORY" },
    { code: "56", speciality: "M.RADIOLOGY&ELECTRICITY" },
    { code: "57", speciality: "PULMONARY MEDICINE" },
    { code: "58", speciality: "PHYSICAL MEDICINE AND REH" },
    { code: "59", speciality: "MATERNAL AND CHILD HEALTH" },
    { code: "60", speciality: "GENERAL MEDICINE" },
    { code: "61", speciality: "RADIO DIAGNOSIS" },
    { code: "62", speciality: "INDUSTRIAL HEALTH" },
    { code: "63", speciality: "SONOGRAPHY" },
    { code: "64", speciality: "GERIATRIC MEDICINE" },
    { code: "65", speciality: "ENDOCRINE SURGERY" },
    { code: "66", speciality: "PUBLIC HEALTH" },
    { code: "67", speciality: "RESPIRATORY DISEASES" },
    { code: "68", speciality: "EMERGENCY MEDICINE" },
    { code: "69", speciality: "CLINICAL RESEARCH" },
    { code: "70", speciality: "SKIN DISEASES" },
    { code: "71", speciality: "PHYSICIAN" },
    { code: "72", speciality: "ENDOSCOPY" },
    { code: "73", speciality: "TUBERCULOSIS & CHEST DISEASES" },
    { code: "74", speciality: "TUBERCULOSIS" },
    { code: "75", speciality: "M. RADIOLOGY THERAPEUTIC" },
    { code: "76", speciality: "NEURO SURGERY" },
    { code: "77", speciality: "TUBERCULOSIS & CHEST DISEASES" },
    { code: "78", speciality: "CHILD HEALTH" },
    { code: "79", speciality: "THORACIC SURGERY" },
    { code: "80", speciality: "GENERAL PRACTICE" },
    { code: "81", speciality: "M.RADIOLOGY&ELECTROLOGY" },
    { code: "82", speciality: "PATHOLOGY & BACTERIOLOGY" },
    { code: "83", speciality: "OPHTHALMIC MEDICINE & SUR" },
    { code: "84", speciality: "HOSPITAL&HEALTH CARE MANA" },
    { code: "85", speciality: "SKIN & VD" },
    { code: "86", speciality: "INDUSTRIAL HYGIENE" },
    { code: "87", speciality: "RADIOTHERAPY" },
    { code: "88", speciality: "CLINICAL PATHOLOGY" },
    { code: "89", speciality: "VENEROLOGY & DERMATOLOGY" },
    { code: "91", speciality: "PHYSICIAN&SUGEON(LCPS)" },
    { code: "92", speciality: "COMMUNITY HEALTH ADMINSTR" },
    { code: "93", speciality: "CLINICAL EMBROLOGY" },
    { code: "94", speciality: "HEALTH & FAMILY WELFARE M" },
    { code: "96", speciality: "VASCULAR SURGERY" },
    { code: "97", speciality: "CRITICAL CARE MEDICINE" },
    { code: "98", speciality: "OBSTETRICS & GYNAECOLOGY" },
    { code: "99", speciality: "D.TUBERCULOUS DISEASES" },
    { code: "100", speciality: "PAEDIATRIC SURGERY" },
    { code: "101", speciality: "PSYCHOLOGICAL MEDICINE" },
    { code: "102", speciality: "PREVENTIVE&SOCIAL MED" },
    { code: "103", speciality: "PAIN&PALLIATIVE MEDICINE" },
    { code: "104", speciality: "INTERNAL MEDICINE" },
    { code: "105", speciality: "PHILOSOPHY" },
    { code: "106", speciality: "SURGICAL ONCOLOGY" },
    { code: "107", speciality: "SURGICAL GASTROENTEROLOGY" },
    { code: "108", speciality: "HEALTH SCIENCES ULTRASONO" },
    { code: "109", speciality: "CLINICAL IMMUNOLOGY" },
    { code: "110", speciality: "TUBERCULOSIS" },
    { code: "111", speciality: "MEDICO LEGAL SYSTEMS" },
    { code: "112", speciality: "MEDICAL COSMETOLOGY" },
    { code: "113", speciality: "GENITO URINARY SURGERY" },
    { code: "114", speciality: "PHYSICIAN&SUGEON(LCPS)" },
    { code: "115", speciality: "REPRODUCTIVE & SEXUAL MED" },
    { code: "116", speciality: "OCCUPATIONAL HEALTH & SAF" },
    { code: "117", speciality: "OTO-RHINO-LARYNGOLOGY" },
    { code: "118", speciality: "PHARMACEUTICAL MARKETING" },
    { code: "119", speciality: "F.M.T." },
    { code: "120", speciality: "PSYCHOLOGY" },
    { code: "121", speciality: "TRANSFUSION MEDICINE" },
    { code: "122", speciality: "CLINICAL CARDIOLOGY" },
    { code: "123", speciality: "SEXUALLY TRANSMITTED DISEASES" },
    { code: "124", speciality: "VENEREOLOGY" },
    { code: "125", speciality: "MIDWIFERY AND GYNAECOLOGY" },
    { code: "126", speciality: "F.R.C.S (ROYAL COLLEGE OF" },
    { code: "127", speciality: "F.R.C.A (ROYAL COLLEGE OF" }
];

export default SpecialityData;
